name: Test and Coverage Verification

on:
  pull_request:

jobs:
  coverage-verification:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: 19
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Generate Tests Report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: WareHouse-Test-Report
          path: 'build/reports/tests/test/'

      - name: Validate coverage
        run: ./gradlew jacocoTestCoverageVerification

      - name: Generate coverage report (If JaCoCo finds violations)
        if: failure()
        run: ./gradlew jacocoTestReport

      - name: Upload Unit Tests Coverage Report (If JaCoCo finds violations)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: WareHouse-Coverage-Report
          path: 'build/reports/jacoco/test/html/'