name: Coverage validation

on:
  pull_request:

jobs:
  coverage:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests and validate coverage
        run: ./gradlew jacocoTestCoverageVerification

      - name: Upload Unit Tests Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: WareHouse-Coverage-Report
          path: 'app/build/reports/coverage/test/debug/'