name: Test coverage verification

on:
  pull_request:

jobs:
  coverage:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Validate coverage
        run: ./gradlew jacocoTestCoverageVerification --no-daemon

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport --no-daemon

      - name: Upload Unit Tests Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: WareHouse-Coverage-Report
          path: 'build/reports/coverage/test/html/'