name: Documentation

on:
  pull_request:

jobs:
  documentation:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: 19
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate documentation
        run: ./gradlew dokkaHtml

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: WareHouse-KDoc-Documentation
          path: 'build/dokka/html'
